// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBddt3TEeSnQ0cltqO7xvc347v5yKy9tUc',
    appId: '1:1070860626302:web:a8eb62803eb51bedf3ab2f',
    messagingSenderId: '1070860626302',
    projectId: 'evently-app-cfbd4',
    authDomain: 'evently-app-cfbd4.firebaseapp.com',
    storageBucket: 'evently-app-cfbd4.firebasestorage.app',
    measurementId: 'G-6D91V0JLZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrSS-dycpdX3rVSy6yks_yISUWQD3eBDI',
    appId: '1:1070860626302:android:66da049919dc266af3ab2f',
    messagingSenderId: '1070860626302',
    projectId: 'evently-app-cfbd4',
    storageBucket: 'evently-app-cfbd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1eswiWhUyGWslSkU4s9v3SCHJQ3qvjc4',
    appId: '1:1070860626302:ios:1bf521b24c7c4a2ef3ab2f',
    messagingSenderId: '1070860626302',
    projectId: 'evently-app-cfbd4',
    storageBucket: 'evently-app-cfbd4.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1eswiWhUyGWslSkU4s9v3SCHJQ3qvjc4',
    appId: '1:1070860626302:ios:1bf521b24c7c4a2ef3ab2f',
    messagingSenderId: '1070860626302',
    projectId: 'evently-app-cfbd4',
    storageBucket: 'evently-app-cfbd4.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBddt3TEeSnQ0cltqO7xvc347v5yKy9tUc',
    appId: '1:1070860626302:web:905b416e591e8a91f3ab2f',
    messagingSenderId: '1070860626302',
    projectId: 'evently-app-cfbd4',
    authDomain: 'evently-app-cfbd4.firebaseapp.com',
    storageBucket: 'evently-app-cfbd4.firebasestorage.app',
    measurementId: 'G-EPLL71PBFT',
  );
}
